### PR TITLE
DNM - test EEs

### PR DESCRIPTION
**Pull request by pabelanger**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1092
Depends-On: https://github.com/ansible-collections/ansible.network/pull/14
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 9b2c58f9b12399e100a2b24454eebe59d8fdcaeb

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now e7ae069d2a526b7a223a97f3c8322b141ca5661d

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Pull request closed without merging**
